export const field = {
  name: {
    name: 'name',
    type: 'text',
    placeholder: 'Name',
    pattern: '.{3,}',
    title: 'Name must be at least 3 characters',
    required: true,
  },
  email: {
    name: 'email',
    type: 'email',
    placeholder: 'Email*',
    required: true,
    pattern: '[a-z0-9._%+-]+@[a-z0-9.-]+.[a-z]{2,4}',
    title: 'Invalid email',
  },
  password: {
    name: 'password',
    type: 'password',
    placeholder: 'Password*',
    required: true,
    pattern: '.{8,}',
    title: 'Password must be at least 8 characters',
  },
  height: {
    name: 'height',
    type: 'text',
    placeholder: 'Height*',
    required: true,
    pattern: '(250)|(10*\\d{1,3})',
    title: 'Please enter a valid number between 100 and 250.',
  },
  age: {
    name: 'age',
    type: 'text',
    placeholder: 'Age*',
    required: true,
    pattern: '(100)|(0*\\d{1,3})',
    title: 'Please enter a valid number between 18 and 100.',
  },
  weight: {
    name: 'weight',
    type: 'text',
    placeholder: 'Current weight*',
    required: true,
    pattern: '(250)|(0*\\d{1,3})',
    title: 'Please enter a valid number between 20 and 250.',
  },
  desiredWeight: {
    name: 'desiredWeight',
    type: 'text',
    placeholder: 'Desired weight*',
    required: true,
    pattern: '(250)|(0*\\d{1,3})',
    title: 'Please enter a valid number between 20 and 500.',
  },
  bloodType: {
    name: 'blodtype',
    type: 'text',
    placeholder: 'Blood Type*',
  },
  filter: {
    type: 'text',
    name: 'filter',
    placeholder: 'filter by name',
  },
};
